### ISSUE TITLE
Primera correcion TP1

### ISSUE THREAD

**Issue by crisszkutnik** [crisszkutnik/2020_K2031_Grupo_5#4]
Solicitamos correccion del TP1. Esta subida una version hecha con la tabla de transicion y otra version con el concepto de hacerlo con structs y pensarlo como una lista enlazada. 

@santiagoferreiros

**Comment by santiagoferreiros** [comment]
Cristian,
Excelente trabajo. Ambas implementaciones.

Para este caso es más sencillo preguntar si el caracter se encuentra entre determinado intervalo de valores. Por decir algo, '0' < caracter < '9'. A que recorrer la cadena con todos los caracteres posibles. Es mi única observación 

PERO, me parece original, y eso lo valoro muchísimo. Felicitaciones por su trabajo. Puede ser muy útil cuando el conjunto de caracteres posibles para cada transición no son consecutivos. En ese caso puede ser conveniente recorrer como cadena hasta que haya una coincidencia =)

Nota: 10 !

@crisszkutnik @ezemartlopez @NicoVillar98 @horosco95
