### ISSUE TITLE
Correcion TP2

### ISSUE THREAD

**Issue by crisszkutnik** [crisszkutnik/2020_K2031_Grupo_5#6]
Solicitamos corrección el TP2

@santiagoferreiros

**Comment by santiagoferreiros** [comment]
Excelente trabajo

@crisszkutnik  @ezemartlopez  @NicoVillar98  @horosco95 

Nota: 9

Hay algunos errores que no clasifica del todo bien.
Por ejemplo con (1+2))

Podría decir algo como , paréntesis sobrante.
Pero está muy muy bien =

Felicitacaciones equipo !!!
