### ISSUE TITLE
Correccion TP3

### ISSUE THREAD

**Issue by crisszkutnik** [crisszkutnik/2020_K2031_Grupo_5#7]
Hola Santi,

esta listo el TP3 para la correccion. En el archivo "Consideraciones.md" hay algunas aclaraciones.

Saludos!

@santiagoferreiros

**Comment by santiagoferreiros** [comment]
Grupo,

EXCELENTE TRABAJO.
Impecable el orden, las aclaraciones.

Nota: 10

FELICITACIONES!
